services:
  db:
    image: mysql:8.0
    restart: always
    container_name: mysql-db
    ports:
      - '3306:3306'
    environment:
      - MYSQL_ROOT_PASSWORD=password
      - MYSQL_DATABASE=MuOnline97
    volumes:
      - ./db:/var/lib/mysql

  phpmyadmin:
    image: phpmyadmin
    restart: always
    container_name: php-my-admin
    ports:
      - "8081:80"
    depends_on:
      - db
    environment:
      # - PMA_HOST=10.10.1.16
      - UPLOAD_LIMIT=200M
      - MEMORY_LIMIT=6G
      - MAX_EXECUTION_TIME=160000
      # - PMA_ABSOLUTE_URI=https://localhost/phpmyadmin
